name: Update Render Status Badge
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Generate Badge URL
        id: badge
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          BADGE_URL=$(node index.js)
          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_OUTPUT
      - name: Update README
        run: |
          sed -i "s|https://img.shields.io/badge/Render-.*|$(echo ${{ steps.badge.outputs.BADGE_URL }})|" README.md
          git config --global user.name "nia-cloud-official"
          git config --global user.email "miltonhyndrex@gmail.com"
          git add README.md
          git commit -m "Update Render status badge"
          git push
